#!/usr/bin/env python

import sys
import time
import argparse

from confparser import ConfParser
from transformer import *

class Txts:

    def __init__(self, styles):
        self.transformer = Transformer(styles)

    def transform_input(self):
        try:
            while True:
                line = sys.stdin.readline()
                if not line:
                    # time.sleep(0.1)
                    continue
                self.__style(line)
        except KeyboardInterrupt:
            pass

    def __style(self, line):
        styled_line = self.transformer.style(line.strip('\n'))
        sys.stdout.write(styled_line + '\n')


def parse_args():
    parser = argparse.ArgumentParser(
        prog='txts',
        description='Prettifies output of console programs.')

    parser.add_argument('-n', nargs=1)
    return parser.parse_args()

def main():
    args = parse_args()
    styles = []
    if args.n:
        style_name = args.n[0]
        styles = ConfParser().get_styles(style_name)

    txts = Txts(styles)
    txts.transform_input()

if __name__ == "__main__":
    main()

